version: "3"
services:
  ec_jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_container
    volumes:
      - src/:/srv/app/src/
      - $SSH_AUTH_SOCK:/ssh-agent #Forward local machine (Host) key to docker container.
      - jenkins_home:/var/jenkins_home
    environment:
      SSH_AUTH_SOCK: /ssh-agent
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  src:
  jenkins_home: